server:
  port: 8082

spring:
  application:
    name: benchmark-central

influx:
  url: http://localhost:8086
  token: ${INFLUX_TOKEN:my-token}
  org: ${INFLUX_ORG:benchmark-org}
  bucket: ${INFLUX_BUCKET:benchmark-metrics}