server:
  port: 8080

spring:
  application:
    name: benchmark-agent

agent:
  source-region: turkey
  central-api-url: http://35.159.232.162:8082
  targets:
    - region: frankfurt
      host: 3.123.34.49
      port: 8081
    - region: istanbul
      host: 83.119.129.151
      port: 8081